authentication-mode: none
#authentication-mode: basic
#authentication-mode: form
#authentication-mode: keycloak

server:
  port: 8090

spring:
  config:
    import: optional:classpath:application-${authentication-mode}.yml
  web:
    resources:
      cache:
        cachecontrol:
          no-store: true
