authentication-mode: none
#authentication-mode: basic
#authentication-mode: form
#authentication-mode: keycloak

server:
  port: 8090

spring:
  resources:
    cache:
      cachecontrol:
        no-store: on
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: secret-webapp
            client-secret: hC0VxkSVOkxzAewulJ2arhfKTYNOWYOQ
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: https://lemur-5.cloud-iam.com/auth/realms/keycloak-training

