authentication-mode: none
#authentication-mode: basic
#authentication-mode: form
#authentication-mode: keycloak

server:
  port: 8090

spring:
  resources:
    cache:
      cachecontrol:
        no-store: on

