#authentication-mode: none
#authentication-mode: basic
#authentication-mode: form
authentication-mode: keycloak

server:
  port: 8090

spring:
  resources:
    cache:
      cachecontrol:
        no-store: on
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: secret-webapp
            client-secret: 5SxcKHdoOEONXdN8riWK4cHYF1fGPMCX
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/training

