version: '3.7'
services:

  postgres:
    container_name: postgres
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: user
      POSTGRES_DB: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: keycloak:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    depends_on:
      - postgres
    ports:
      - 8443:8443
      - 8080:8080
      - 9990:9990
    command:
      - -Djboss.bind.address.management=0.0.0.0
    environment:
      DB_USER: user
      DB_PASSWORD: pwd
      DB_ADDR: postgres
      DB_PORT: 5432
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      keycloak_profile_feature_token_exchange: enabled

  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_PROVIDER: "keycloak"
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: "Keycloak"
      OAUTH2_PROXY_COOKIE_SECRET: "AZERTYUIOPQSDFGH"
      OAUTH2_PROXY_SCOPE: "openid"
      #OAUTH2_PROXY_INSECURE_OIDC_SKIP_ISSUER_VERIFICATION: "true"

      OAUTH2_PROXY_CLIENT_ID: "oauth2-proxy"
      OAUTH2_PROXY_CLIENT_SECRET: "80e88c33-7a84-4240-b3c7-083466561792"
      # The host:port used for fetching userinfo needs to be the same as the one used to login
      # Clearly speaking OAUTH2_PROXY_LOGIN_URL and OAUTH2_PROXY_VALIDATE_URL must use the same host:port
      OAUTH2_PROXY_LOGIN_URL: "http://keycloak:8080/auth/realms/formatiojn/protocol/openid-connect/auth"
      OAUTH2_PROXY_REDEEM_URL: "http://keycloak:8080/auth/realms/formatiojn/protocol/openid-connect/token"
      OAUTH2_PROXY_VALIDATE_URL: "http://keycloak:8080/auth/realms/formatiojn/protocol/openid-connect/userinfo"
      OAUTH2_PROXY_REDIRECT_URL: "http://localhost:4180/oauth2/callback"
      OAUTH2_PROXY_UPSTREAMS: "http://172.23.0.1:8090"
      OAUTH2_PROXY_KEYCLOAK_GROUP: "WEBAPP"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
    ports:
      - 4180:4180

  openldap:
    container_name: openldap
    image: osixia/openldap:1.3.0
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_ADMIN_PASSWORD: admin
      LDAP_ORGANISATION: test
      LDAP_DOMAIN: formation

# login needs to  be done with user dn: cn=admin,dc=keycloak,dc=org

  phpldapadmin:
    container_name: ldap-admin
    image: osixia/phpldapadmin
    ports:
      - 6443:443
    environment:
      PHPLDAPADMIN_HTTPS: "true"
      PHPLDAPADMIN_LDAP_HOSTS: openldap


volumes:
  postgres_data:
    driver: local

