version: '3.7'
services:

  postgres:
    container_name: postgres
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: user
      POSTGRES_DB: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: keycloak:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    depends_on:
      - postgres
    ports:
      - 8443:8443
      - 8080:8080
      - 9990:9990
    environment:
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: pwd
      KC_DB_USERNAME: user
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: none


  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    environment:
      # General configuration ==> DO NOT CHANGE
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_PROVIDER: "keycloak"
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: "Keycloak"
      OAUTH2_PROXY_COOKIE_SECRET: "AZERTYUIOPQSDFGH"
      OAUTH2_PROXY_SCOPE: "openid"
      OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY: "true"
      OAUTH2_PROXY_COOKIE_SECURE: "false"


      # Environment specific configuration ==> CHANGE IT
      OAUTH2_PROXY_CLIENT_ID: "oauth2-proxy"
      OAUTH2_PROXY_CLIENT_SECRET: "80e88c33-7a84-4240-b3c7-083466561792"
      # The host:port used for fetching userinfo needs to be the same as the one used to login
      # Clearly speaking OAUTH2_PROXY_LOGIN_URL and OAUTH2_PROXY_VALIDATE_URL must use the same host:port
      OAUTH2_PROXY_LOGIN_URL: "http://keycloak:8080/auth/realms/formatiojn/protocol/openid-connect/auth"
      OAUTH2_PROXY_REDEEM_URL: "http://keycloak:8080/auth/realms/formatiojn/protocol/openid-connect/token"
      OAUTH2_PROXY_VALIDATE_URL: "http://keycloak:8080/auth/realms/formatiojn/protocol/openid-connect/userinfo"
      OAUTH2_PROXY_REDIRECT_URL: "http://localhost:4180/oauth2/callback"
      OAUTH2_PROXY_UPSTREAMS: "http://172.23.0.1:8090"


      # Authorization configuration
      OAUTH2_PROXY_ALLOWED_GROUPS: "WEBAPP"
      OAUTH2_PROXY_EMAIL_DOMAINS: "secret.com"
    ports:
      - 4180:4180

  openldap:
    container_name: openldap
    image: osixia/openldap:1.3.0
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_ADMIN_PASSWORD: admin
      LDAP_ORGANISATION: test
      LDAP_DOMAIN: formation

# login needs to  be done with user dn: cn=admin,dc=keycloak,dc=org

  phpldapadmin:
    container_name: ldap-admin
    image: osixia/phpldapadmin
    ports:
      - 6443:443
    environment:
      PHPLDAPADMIN_HTTPS: "true"
      PHPLDAPADMIN_LDAP_HOSTS: openldap


  smtp:
    image: maildev/maildev:2.0.0-beta3
    container_name: smtp
    ports:
      - 1080:1080
      - 1025:1025


volumes:
  postgres_data:
    driver: local

