server:
  port: 8090

keycloak:
  enabled: true
  realm: formatiojn
  auth-server-url: http://localhost:8099/auth
  ssl-required: none
  resource: back
  bearer-only: true
  securityConstraints:
  - authRoles:
    - admin
    securityCollections:
    - name: admin endpoint
      patterns:
      - /messages/admin
  - authRoles:
    - admin
    - user
    securityCollections:
    - name: user endpoint
      patterns:
      - /messages/user
