#authentication-mode: none
#authentication-mode: basic
authentication-mode: keycloak

spring:
  resources:
    cache:
      cachecontrol:
        no-cache: on
        max-age: 1s

logging:
  level:
    org.keycloak: debug

server:
  port: 8090

keycloak:
  realm: formatiojn
  resource: springboot
  credentials:
    secret: a4cbc0da-6d60-44b7-b4c6-b13dda136a68
  auth-server-url: http://localhost:8080/auth
  #realm: test-tristan
  #resource: formation
  #credentials:
  #  secret: 48042d0e-daca-46bd-8126-de70ccbee4f9
  #auth-server-url: https://iam.cloud-iam.com/auth
  bearer-only: false
  public-client: false
#  policy-enforcer-config:
#    enforcement-mode: ENFORCING
#  securityConstraints:
#  - authRoles:
#    - user
#    securityCollections:
#    - name: admin endpoint
#      patterns:
#      - /*
